## 1. List/Dict/Set comprehensions: 


A concise way to create lists, dictionaries, and sets using a single line of code.

In [62]:
# list comprehension
_list = [x**2 for x in range(1, 11)]

# nested list comprehension to flatten list
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

flat_list = [num # append to list
            for row in matrix # outer loop
            for num in row] # inner loop

print(_list)
print(flat_list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
# dictionary comprehension
_dict = {var:var ** 2 for var in range(1, 11) if var % 2 != 0}

# set comprehension
# create a set of squares of numbers from 1 to 10
_set = {x**2 for x in range(1, 11)}

# generator comprehension
_gen = (x**2 for x in range(1, 11))

print(_dict)
print(_set)
print(list(g for g in _gen))

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81}
{64, 1, 4, 36, 100, 9, 16, 49, 81, 25}
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

## 2. enumerate

Allows you to iterate over a sequence while keeping track of the index.

In [64]:
for idx, value in enumerate(["a", "b", "c", "d"]):
    if idx % 2 == 0:
        print(value)

a
c

## 3. Zip

Combines two or more sequences, creating pairs of corresponding elements.

In [29]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]

# iterate over both arrays simultaneously
for a, b in zip(x, y):
    print(a, b, a + b, a * b)

1 5 6 5
2 6 8 12
3 7 10 21
4 8 12 32

## 4. Generators

Functions that allow you to create iterators using the yield keyword.

In [13]:
def fib_gen(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b


res = fib_gen(10)
print(list(r for r in res))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

## 5. Lambda functions

Small, anonymous functions that can be defined on-the-fly.

In [20]:
numbers = range(10)

even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

print(even_numbers)

[0, 2, 4, 6, 8]

In [27]:
import pandas as pd

data = {
    "sales_person": ["Alice", "Bob", "Charlie", "David"],
    "sale_amount": [100, 200, 300, 400],
}
df = pd.DataFrame(data)

threshold = 250
df["above_threshold"] = df["sale_amount"].apply(
    lambda x: True if x >= threshold else False
)
df

  sales_person  sale_amount  above_threshold
0        Alice          100            False
1          Bob          200            False
2      Charlie          300             True
3        David          400             True

## 6. map, filter, reduce

Built-in functions that allow you to apply a function to every element in a sequence.

In [93]:
numbers = range(10)

# Use map(), filter(), and reduce() to preprocess and aggregate the list of numbers
even_numbers = filter(lambda x: x % 2 == 0, numbers)
squares = map(lambda x: x**2, even_numbers)
sum_of_squares = reduce(lambda x, y: x + y, squares)


print(f"Sum of the squares of even numbers: {sum_of_squares}")

Sum of the squares of even numbers: 120

## 7. any and all

any and all: Functions to check if any or all elements in an iterable are truthy.

In [ ]:
data = [1, 3, 5, 7]
print(any(x % 2 == 0 for x in data))
print(all(x % 2 == 1 for x in data))

False
True

## 8. next 

Retrieve the next item from an iterator, with a default value if the iterator is exhausted

In [1]:
import random 

def random_numbers():
    while True:
        yield random.random()

# Use next() to find the first number greater than 0.9
num = next(x for x in random_numbers() if x > 0.9)

print(f"First number greater than 0.9: {num}")

First number greater than 0.9: 0.9444805819267413

## 9. Defaultdict

A dictionary subclass that provides a default value for nonexistent keys.

In [30]:
from collections import defaultdict

count = defaultdict(int)
for item in ['a', 'b', 'a', 'c', 'b', 'a']:
    count[item] += 1

count

defaultdict(int, {'a': 3, 'b': 2, 'c': 1})

## 10. partial

In [ ]:
from functools import partial

def add(x, y):
    return x + y

increment = partial(add, 1)
increment(1)

2

## 11. lru_cache

functools.lru_cache: Decorator to memoize a function using a Least Recently Used (LRU) cache.

In [73]:
from functools import lru_cache

@lru_cache(maxsize=None)
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

fibonacci(1e3)

4.346655768693743e+208

In [74]:
fibonacci.cache_info()

CacheInfo(hits=998, misses=1001, maxsize=None, currsize=1001)

## 12. data classes

A concise way to define classes that are used to store data.

In [ ]:
from dataclasses import dataclass

@dataclass
class Person:
    name: str
    age: int
    city: str

p = Person("Alice", 30, "New York")
print(p)

Person(name='Alice', age=30, city='New York')

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a605a3e6-1564-47b2-94e7-842290ba7692' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>